#!/bin/bash
#SBATCH -M truba 
#SBATCH -p mid2
##SBATCH -A modarresi
#SBATCH -A tbag78
#SBATCH -J AB1
#SBATCH -N 1 
#SBATCH -n 32
#SBATCH --time=1:15:00 
#SBATCH --mail-type=ALL
#SBATCH --output=out
#SBATCH --error=err

echo "SLURM_NTASKS= $SLURM_NTASKS" 
echo "SLURM_TASKS_PER_NODE= $SLURM_TASKS_PER_NODE" 
echo "SLURM_NNODES= $SLURM_NNODES"
echo "SLURM_NODELIST= $SLURM_NODELIST" 
echo "SLURM_CPU_BIND= $SLURM_CPU_BIND" 
echo "SLURM_JOB_CPUS_PER_NODE= $SLURM_JOB_CPUS_PER_NODE" 

. /usr/share/Modules/init/bash
source /truba/sw/centos7.3/comp/intel/PS2018-update2/bin/compilervars.sh intel64

ulimit -s unlimited
ulimit -l unlimited
export OMP_NUM_THREADS=1

mpirun /truba/home/modarresi/vasp/vasp_std
